// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udolzgltelxvqssapaax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkb2x6Z2x0ZWx4dnFzc2FwYWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODk3MTUsImV4cCI6MjA2ODY2NTcxNX0.bcKcWA5zsrIMHqey_zu0t95GIXqc7c7nzCi9YVDv_r4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});